### ISSUE TITLE
En tant que admin, je peux ajouter une nouvelle via ferrata, afin de les afficher sur le site

### ISSUE THREAD

**Issue by maidmaid** [ZHB/hesso-viaferrata#1]
**Tâches**
- [x] Définir les champs nécessaires et la structure
- [x] Implémenter la/les classe(s) métier(s) nécessaire(s)
- [x] Implémenter mécanisme de validation des entrées de l'utilisateur
- [x] Implémenter bouton "Enregistrer nouvelle VF"
- [x] Enregistrer la nouvelle VF dans la base de donnée
- [ ] Mise en forme du fomulaire
- [ ] Backend pour l'admin

**Contrôlé par:**
- [x] Affichage de la VF créé dans la liste des VF
- [x] Persistance de la nouvelle VF

Description par guluk

**Comment by maidmaid** [comment]
- [] caracteristic parent <=> child

**Comment by guluk** [comment]
@ZHB lors de la séance de vendredi matin, il en résulte une (nouvelle) tâche pour les séctions des VF ou qu'est-ce que nous avons finalement décidé pour cet histoire? Tu te rappelles?

**Comment by ZHB** [comment]
@guluk non pas de nouvelle tâche pour cette US. Juste mettre un peu au propre (traductions). 

La nouvelle tâche c est pour l'affichage sous forme de liste avec un filtre et la géolocalisation par pays.

**Comment by maidmaid** [comment]
La conclusion de la discussion des sections de VF, c'était de garder cette feature pour plus tard.
