### ISSUE TITLE
En tant que visiteur, je peux filtrer les via ferrata plus précisément, afin d'affiner ma recherche

### ISSUE THREAD

**Issue by maidmaid** [ZHB/hesso-viaferrata#11]
- [ ] créer un formulaire de filtres sur le côté (à la Booking.com)
- [ ] Récupérer les VF selon les critères
- [ ] Créer l'affichage dans template Twig

**Comment by ZHB** [comment]
Finalement semblable à la recherche effectuée pour la #10. Je propose donc de ne rien faire de plus pour ces filtres puisque le formulaire de recherche on le laisse au sommet de chaque page pour qu'il soit facilement accessible.
