### ISSUE TITLE
En tant que membre, je peux ajouter des commentaires par VF, afin de donner mon opinion

### ISSUE THREAD

**Issue by maidmaid** [ZHB/hesso-viaferrata#12]
- [x] Utiliser pour cela [FOSCommentBundle ](https://github.com/FriendsOfSymfony/FOSCommentBundle)
- [x] Installer/configurer FOSCommentBundle
- [x] modifier l'affichage (si nécessaire)

**Comment by ZHB** [comment]
J'ai essayé vite fait FOSCommentBundle. L'installation est relativement simple et une configuration de base se réalise en env. 20 - 25 minutes en suivant la doc. 

Il faut ensuite ajouter un peu de temps pour la mise en page qui n'est pas top de base.
