### ISSUE TITLE
Mettre une version de test en qualité sur Swisscenter

### ISSUE THREAD

**Issue by maidmaid** [ZHB/hesso-viaferrata#30]
- [ ] demander les accès au client
- [ ] pousser le projet en prod

**Comment by ZHB** [comment]
Est-ce que qqun à demandé les accès ?

**Comment by maidmaid** [comment]
Nope, je l'ai pas encore fait. Je regarde ce soir.

**Comment by maidmaid** [comment]
J'ai envoyé le mail. J'attends la réponse du client.

**Comment by ZHB** [comment]
http://chablair.ch/vf/web
