### ISSUE TITLE
En tant que admin, je peux me déconnecter du backend, afin de fermer ma session

### ISSUE THREAD

**Issue by maidmaid** [ZHB/hesso-viaferrata#5]
**Tâches**
- [x] Implémenter un bouton de logout
- [x] Implémenter mécanisme de logout (+ gestion de la session)
- [x] Implémenter la redirection vers la page de login ou la page VF officielle (à discuter avec client) 

**Contrôlé par:**
- [x] Redirection sur le site souhaité après déconnexion

Description par guluk

**Comment by meons** [comment]
Issue traitée dans les commits de l'issue #4
