### ISSUE TITLE
En tant que visiteur, je peux filtrer les via ferrata par pays, afin de disposer d'une meuilleure navigation

### ISSUE THREAD

**Issue by maidmaid** [ZHB/hesso-viaferrata#6]
**Tâches**
- [ ] Implémenter une interface pour afficher toutes les VF dans une liste
- [ ] Implémenter des éléments pour filtrer les VF (DropDownList?)
- [ ] Implémenter mécanisme de mise à jour de la page (mots clés PostBack / AJAX)
- [ ] Implémenter la possibilité de choisir (cliquer sur) une VF afin d'afficher son détail

**Contrôlé par:**
- [ ] Affichage correcte du résultat du filtrage
- [ ] State management correct
- [ ] Affichage/redirection vers le détail d'une VF lors d'un clique sur une VF dans la liste

Description par guluk

**Comment by ZHB** [comment]
Cette issue est finalement à modifier par rapport à l'issue #10 puisque la #10 redirige l'utilisateur en fonction de son pays sur la liste des VF correspondantes lorsqu'il consulte l'url `app_dev.php/viaferrata`

De plus, un filtre de recherche sur toutes les pages est présent donc pas besoin d'en faire un autre.

**Au final je propose de ne rien faire de cette issue et d'en prendre une nouvelle à ton retour.**
