### ISSUE TITLE
En tant que visiteur, je dispose d'une carte interactive, afin de localiser les via ferrata

### ISSUE THREAD

**Issue by maidmaid** [ZHB/hesso-viaferrata#7]
- [x]  Afficher les VF sur une carte GoogleMaps (ou avec [leaflet](http://leafletjs.com/))
- [ ] Utiliser les [clusters GoogleMaps](https://developers.google.com/maps/articles/toomanymarkers) si nécessaire 
- [ ] Créer pour chaque marker une affichage HTML avec lien renvoyant vers la VF. cf. #8

**Comment by ZHB** [comment]
@guluk, comme dit dans la PR, je propose de mettre ta carte aux emplacements suivants : 
- sur la vue de la route `viaferrata_index_by_country`, au sommet de la liste. Il faut simplement t'arranger de n'afficher que les VF du pays en question. Il faut également gérer le centrage et le zoom de la carte en fonction des VF récupérées
- sur la vue de la route du détail d'une VF `viaferrata_show_by_country`
