### ISSUE TITLE
En tant que visiteur, je peux cliquer sur un marqueur de la carte afin d'accéder au détail de la via ferrata

### ISSUE THREAD

**Issue by maidmaid** [ZHB/hesso-viaferrata#8]
- [ ] cf. #7

**Comment by guluk** [comment]
@maidmaid pour faire propre il faudrait utiliser (et donc installer via le composer) le [FOSJsRoutingBundle](https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/doc/index.md#installation) non? Alternativement je peux faire un truc comme:
`var url = '{{ path("viaferrata_show", { 'id': 'PLACEHOLDER' }) }}';`
`url.replace('PLACEHOLDER', id);`
`var html = ('<a href="' + url + '">' + val['name'] + ', ' + val['city'] + '</a>');`

**Comment by maidmaid** [comment]
L’alternative serait plutôt de retourner la route ``viaferrata_show`` compilée pour chacune des VF dans le json de résultat. Mais l'idéal, c'est d'utiliser le FOSJsRoutingBundle effectivement.
